server:
  port: 8081
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8083
---
spring:
  profiles: prod
server:
  port: 8084
#persion:
#    name: 王久一
#    age: 18
#    weight: 125
#    boss: false
#    birth: 2018/5/5
#    maps: {k1: v1,k2: v2}
#    list:
#      - wangli
#      - wangbai
#    dog:
#      name: xiaogou
#      age: 2
